worker_processes auto;

events {
  worker_connections 1024;
}

http {
  include       mime.types;
  default_type  application/octet-stream;
  sendfile      on;

  # Redirect plain HTTP (8880) to HTTPS (8443)
  server {
    listen 80;
    server_name ztna.demo.local;
    return 301 https://$host:8443$request_uri;
  }

  server {
    listen 443 ssl;
    server_name ztna.demo.local;

    ssl_certificate     /etc/nginx/certs/ztna.demo.local.crt;
    ssl_certificate_key /etc/nginx/certs/ztna.demo.local.key;
    ssl_protocols       TLSv1.2 TLSv1.3;

    location / {
      proxy_pass http://fastapi:8000;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }
  }
}
